-- Tabla de Usuarios
CREATE TABLE "Users" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  eliminar BOOLEAN DEFAULT true NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- Tabla de Cursos
CREATE TABLE "Courses" (
  id SERIAL PRIMARY KEY,
  userId INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  eliminar BOOLEAN DEFAULT true NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES "Users" (id) ON DELETE CASCADE
);
-- Tabla de Lecciones
CREATE TABLE "Lessons" (
  id SERIAL PRIMARY KEY,
  courseId INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  eliminar BOOLEAN DEFAULT true NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (courseId) REFERENCES "Courses" (id) ON DELETE CASCADE
);
CREATE TABLE "LessonContent" (
  id SERIAL PRIMARY KEY,
  lessonId INT NOT NULL,
  type VARCHAR(255) NOT NULL,  -- e.g., "document", "image", "video"
  url VARCHAR(255) NOT NULL,     -- URL or path to the content file
  FOREIGN KEY (lessonId) REFERENCES "Lessons" (id) ON DELETE CASCADE
);
-- Tabla de Comentarios
CREATE TABLE "Comments" (
  id SERIAL PRIMARY KEY,
  lessonId INT NOT NULL,
  userId INT NOT NULL,
  content TEXT NOT NULL,
  eliminar BOOLEAN DEFAULT true NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lessonId) REFERENCES "Lessons" (id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES "Users" (id) ON DELETE CASCADE
);
